### ISSUE TITLE
Glossary entry

### ISSUE THREAD

**Issue by tabar** [jamstack/jamstack.org#396] opened 2020-10-07 16:19 UTC
Please update the glossary entry page layout to match the figma.  Happy to work with you to merge the two layouts. https://www.figma.com/file/7nBwzGu2tnmFqNCbUUzdor/Jamstack.org?node-id=0%3A1

**Comment by zachleat** [comment] 2021-07-12 21:15
Duplicate of #395.

**Closed by zachleat** 2021-07-12 21:15 UTC
